title:              Bacalagers Group Clean Blogs
email:              halo@bacalagers.com
description:        BacalagersMedia.Githup.io adalah portal berita terbaru dan terkini, gaya hidup, peluang usaha bisnis, tips kesehatan, tempat wisata, inspirasi dan motivasi, dan lainnya.
author:             Bacalagers Media
baseurl:            "/index.html"
url:                "https://bacalagersmedia.github.io"

# Social Profiles
twitter_username:   bacalagersmedia
github_username:    bacalagersmedia
facebook_username:  bacalagersmedia
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-85014317-6 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
